#!/bin/sh

# Modify this if you move the location of the jar file.
sv_jar="`dirname $0`/sv.jar"

# The svuti.script.name is used when showing usage for --help options.
java -D"sv.scriptname=$0" -jar "$sv_jar" "$@"
